name = "SpikingNN"
uuid = "d87a7e5a-a546-11e9-029a-ebfb0c165160"
authors = ["Tenzin Chan <tenzin_chan@mymail.sutd.edu.sg>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
